<?php

namespace Iss\ConferenceBundle\Repository;

/**
 * PresentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForUser($user_id = null)
    {
        $qb = $this->createQueryBuilder('p');

        if ($user_id) {
            $qb->andWhere('p.owner = :user_id')
                ->setParameter('user_id', $user_id);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
