presentation_index:
    path:     /
    defaults: { _controller: "IssConferenceBundle:Presentation:index" }
    methods:  GET

presentation_show:
    path:     /{id}/show
    defaults: { _controller: "IssConferenceBundle:Presentation:show" }
    methods:  GET

presentation_new:
    path:     /new
    defaults: { _controller: "IssConferenceBundle:Presentation:new" }
    methods:  [GET, POST]

presentation_edit:
    path:     /{id}/edit
    defaults: { _controller: "IssConferenceBundle:Presentation:edit" }
    methods:  [GET, POST]

presentation_delete:
    path:     /{id}/delete
    defaults: { _controller: "IssConferenceBundle:Presentation:delete" }
    methods:  DELETE
